### ISSUE TITLE
Colorpicker throwing an exception in web

### ISSUE THREAD

**Issue by AlbertDavid94** [mchome/flutter_colorpicker#18]
Hi,

the flutter_colorpicker is throwing an exception in the web-version.

This happens as soon as I pick a color.

In the build-version `Another exception was thrown: Instance of 'minified:ep<void>'`

In the development-version I get a very long error:

```
stack_trace_mapper.js:261 Uncaught Bad state: Source maps are not done loading.
    at Object.a (http://localhost:42747/stack_trace_mapper.js:261:3)
    at ct.k6 (http://localhost:42747/stack_trace_mapper.js:2650:23)
    at Object.iH (http://localhost:42747/stack_trace_mapper.js:218:69)
    at jy (http://localhost:42747/stack_trace_mapper.js:2371:10)
    at Object.<anonymous> (http://localhost:42747/stack_trace_mapper.js:2365:42)
    at dart._StackTrace.new.toString (http://localhost:42747/dart_sdk.js:6060:29)
    at Object._toString [as toString] (http://localhost:42747/dart_sdk.js:4431:26)
    at new assertions.DiagnosticsStackTrace.new (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:3467:212)
    at binding$.FlutterErrorDetailsForPointerEventDispatcher.new.debugFillProperties (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:3209:24)
    at http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:2313:38
    at assertions._FlutterErrorDetailsNode.new.get builder (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:2316:28)
    at assertions._FlutterErrorDetailsNode.new.get builder [as builder] (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:3481:27)
    at assertions._FlutterErrorDetailsNode.new.getProperties (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:2328:54)
    at diagnostics$.TextTreeRenderer.new.[_debugRender] (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:1137:37)
    at diagnostics$.TextTreeRenderer.new.render (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:1051:34)
    at Function.dumpErrorToConsole (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:3315:142)
    at Function.reportError (http://localhost:42747/packages/flutter/src/foundation/debug.dart.js:3404:76)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:42747/packages/flutter/src/gestures/binding.dart.js:144:35)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:42747/packages/flutter/src/gestures/binding.dart.js:117:14)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:42747/packages/flutter/src/gestures/binding.dart.js:91:34)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:42747/packages/flutter/src/gestures/binding.dart.js:82:65)
    at Object._invoke1 (http://localhost:42747/dart_sdk.js:164821:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:42747/dart_sdk.js:162115:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:42747/dart_sdk.js:142725:24)
    at http://localhost:42747/dart_sdk.js:143062:26
    at http://localhost:42747/dart_sdk.js:143027:16
    at HTMLElement.<anonymous> (http://localhost:42747/dart_sdk.js:142805:11)
```

**Comment by mchome** [comment]
Hmmm, I think this is a flutter's bug more than mine.
You may want to test other flutter version or channel.

**Comment by AlbertDavid94** [comment]
@mchome I'm not sure, I'm quite new to flutter. It only happens on the web version. On my phone, everything runs perfect. Should I post this issue in the flutter repository?
